server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres_db?currentSchema=spring
    username: postgres_user
    password: postgres_password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
#    open-in-view: false
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yml